### ISSUE TITLE
[QUESTION] Is Command chaining supported?

### ISSUE THREAD

**Issue by atetevoortwis** [tiangolo/typer#107]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Is it possible to 'chain' commands in a single Typer call? Typical usecase for us would be an application where we have a CLI app to do input->processing->output kind of tasks, and for all three there are multiple variants with different options, but they can be combined in a lot of ways.

### Additional context
We currently use [Google Fire](https://github.com/google/python-fire) for our CLI app (which I was surprised not to found in the Inspiration section), which [does this](https://github.com/google/python-fire/blob/master/docs/guide.md#chaining-function-calls) by saving intermediate results in a class containing all 'Commands'.

**Comment by kalzoo** [comment]
+1 (I think).

I'm packaging a CLI within a docker image, and it's important that I can configure the `entrypoint` with a root command and argument, but then that further arguments and commands can be appended as docker `command`s.

I've been all through the `typer` docs, which were a great intro - but without inline documentation in the code, the next step is to ask here.

For example:

Using the `reigns` example from your docs (loosely), imagine a command

```
python reigns.py UNIVERSE_NAME conquer REIGN_NAME
```

or something to that effect. I'd be just as happy with those as args or options - similar to how `git` itself allows mixing of args, flags, and options in almost any order. It does help that `conquer` remains a command, since that's the power of `typer`, otherwise we would just make _everything_ an argument or option:

```
python reigns.py --universe_name UNIVERSE_NAME --operation conquer --reign_name REIGN_NAME
```

That discards much of what makes typer great and quick to set up, since everything is now packed into one root command. But it does allow me to draw a line between a static entrypoint and dynamic commands:

```
python reigns.py --universe_name UNIVERSE_NAME ||<entrypoint --- command>|| --operation conquer --reign_name REIGN_NAME
```

I did try just sending options out of order:

```
python reigns.py --universe_name UNIVERSE_NAME conquer REIGN_NAME
# Error: no such option: --universe_name
```

Putting it back in order fixed the error, but doesn't meet my docker ordering requirement:

```
# This works
python reigns.py  conquer REIGN_NAME --universe_name UNIVERSE_NAME
```

Best-case scenario, all commands in the tree would receive all options. Callbacks don't appear to serve this use case, since the option's value is needed by the command.

Is there a better way?

**Comment by JeromeK13** [comment]
Hey Guys

Yes this can be activated by setting `chain=True` like this:

```python
app = typer.Typer(chain=True)
```

**Comment by pmsoltani** [comment]
@JeromeK13 would you please provide a more detailed example? How, for instance, do I name the command that executes other commands in sequence?

Appreciate your help in advance!

**Comment by JeromeK13** [comment]
```python
import typer

# Init CLI and logger instance
cli = typer.Typer(chain=True)

@cli.command('my_command_name')
def my_function_name():
    typer.echo("Chain 1")

@cli.command('my_command_name2')
def my_function_name():
    typer.echo("Chain 2")

if __name__ == "__main__":
    cli()

```

So if you now run the CLI you can do the following (the command will execute in the order they provided)
`python3 mycli.py my_command_name my_command_name2`

**Comment by pmsoltani** [comment]
@JeromeK13 thanks for your prompt reply. I think perhaps "chaining commands" is not what I wanted. This is what I had in mind (using Click):

```python3
@click.command()
@click.option("--with-testdb/--no-with-testdb", default=False)
@click.pass_context
def reset(ctx):
    """Inits and seeds the database automatically."""
    ctx.invoke(init, with_testdb=with_testdb)
    ctx.invoke(seed)

    return None
```

After some fiddling with the code, I arrived at this:

```python3
@cli.command()
def reset(ctx: typer.Context, with_testdb: bool = False):
    """Inits and seeds the database automatically."""
    ctx.invoke(init, with_testdb)
    ctx.invoke(cyan)
```

Anyway, thanks again for your time.

**Comment by Nitinsiwach** [comment]
This should be made a part of the documentation. Great package otherwise

**Comment by svlandeg** [comment]
[Maintenance note]: I'll go ahead and close this issue as there seems to be a valid workaround. In case there are follow-up questions, please open a new thread on the [discussion forum](https://github.com/tiangolo/typer/discussions) 🙏
