### ISSUE TITLE
dash input with Path option for json file with Pydantic validation

### ISSUE THREAD

**Issue by gilesw-vion** [tiangolo/typer#156]
### First check

* [* ] I used the GitHub search to find a similar issue and didn't find it.
* [*] I searched the Typer documentation, with the integrated search.
* [*] I already searched in Google "How to X in Typer" and didn't find any information.
* [*] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I use a `pathlib.Path` option with `allow_dash=True`  to input json  and parse into a pydantic BaseModel class

### Additional context

I was wondering if  someone had an  example of this - I want to  either input a json file  or default to '-' and take json from input then parse into a pydantic  model. Obviously if dash is not used then I want  to do validation checks on the file to ensure it exists, is readable, is not directory etc. 

Not  sure  if I need to make the Path option typing.Optional  if I'm allowing '-'? Not sure what the other validators do in  this case? Not a lot in the  documentation on this.

**Comment by samueldeklund** [comment]
It got a little complicated along the way, but I developed a workable solution. I figured out that the `allow_dash` parameter doesn't magically take stdin and save it to your variable if the input is a dash, it just "allows" a dash to be a valid input. You still have to process the input based on the value.

Suppose I have `main.py`:

``` python
import sys
import typer

app = typer.Typer()

@app.callback(invoke_without_command=True)
def main(value: typer.FileText = typer.Argument(..., allow_dash=True)):
    """Echo out the input from value."""
    value = sys.stdin.read() if value == "-" else value.read()
    typer.echo(value)

if __name__ == "__main__":
    app()
```

Then you can do

``` bash
echo hello world | python main.py -
# hello world
```

or

``` bash
python main.py file.txt
# prints out contents of file
```

It works with a `typer.Option` as well. 

I agree that this is not clear in the documentation. In fact, I couldn't even find a good example anywhere for Typer OR Click. This took a bunch of experimentation. A good example in the docs would have helped a ton. What would be even better is that if I set `allow_dash=True` and the input is `"-"`, then the value gets set to `sys.stdin` instead of trying to treat it like a file.

**Comment by tiangolo** [comment]
Thanks for the help @samueldeklund! 🍰 

Does that solve your use case @gilesw-vion ? If that's the case, you can close the issue. ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
