### ISSUE TITLE
[BUG] Typer malfunctions when installed as entrypoint with Poetry

### ISSUE THREAD

**Issue by louwers** [tiangolo/typer#159]
### Describe the bug

When installing a package that contains a entrypoint to a script, Typer malfunctions.

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

* Create a file `main.py` with:

```
name = "typer_test"
version = "0.1.0"
description = ""
authors = ["Author <author@compan.comi>"]

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
script = 'script:main'
```

* Create `script.py` with:

```py
import typer


def main(name: str):
    typer.echo(f"Hello {name}")


if __name__ == "__main__":
    typer.run(main)
```

* `mkdir typer_test && touch typer_test/__init__.py`

* `poetry install`

* Now `poetry run script` results in 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: main() missing 1 required positional argument: 'name'
```

* `script` results in:

```
Traceback (most recent call last):
  File "/home/bart.local/sandbox/typer_test/venv/bin/script", line 11, in <module>
    load_entry_point('typer-test', 'console_scripts', 'script')()
TypeError: main() missing 1 required positional argument: 'name'
```

### Expected behavior

```
Usage: script [OPTIONS] NAME
Try "script --help" for help.

Error: Missing argument 'NAME'.
```

### Environment

* OS: Linux
* Typer Version 0.3.2
* Python 3.6.11

### Additional context

[Poetry](https://github.com/python-poetry/poetry) is a dependency manager.

**Comment by tom-on-the-internet** [comment]
Hello @louwers 

The following works with Poetry.

```
import typer

app = typer.Typer()


@app.command()
def main(name: str):
    typer.echo(f"Hello {name}")


def run() -> None:
    """Run commands."""
    app()
```

and your script would be
```
[tool.poetry.scripts]
script = 'script:run'
```

My apologies in advance if this isn't useful to you. I'm new to Poetry/Typer/Python in general.

**Comment by alexifm** [comment]
Hey @tom-on-the-internet , quick question but why not use direct the entrypoint to `app`:
```
[tool.poetry.scripts]
script = 'script:app'
```
Is there something about the entrypoint requiring a function and not a callable object?

**Comment by tom-on-the-internet** [comment]
> Hey @tom-on-the-internet , quick question but why not use direct the entrypoint to `app`:
> 
> ```
> [tool.poetry.scripts]
> script = 'script:app'
> ```
> 
> Is there something about the entrypoint requiring a function and not a callable object?

@alexifm Honestly cannot remember. I was using Python for a few weeks and tried out these tools. Have since decided to to invest too much time in Python. But Typer and Fast Api were great.

**Comment by alextremblay** [comment]
Can this issue be closed? This doesn't appear to have been a bug. It might have been considered an opportunity for documentation, but the "fix" for this issue is already documented here: https://typer.tiangolo.com/tutorial/package/#add-a-script

**Comment by pmsoltani** [comment]
I followed the documentation at [https://typer.tiangolo.com/tutorial/package/](https://typer.tiangolo.com/tutorial/package/)

I'm using `poetry==1.1.4` and when using `poetry install` (like the image below), it does not install my own package:

![image](https://user-images.githubusercontent.com/25427031/103127956-b6304980-46a8-11eb-9950-0c7852f5b532.png)

The last line `- Installing rick-portal-gun (0.1.0)` won't print out. Consequently, running `rick-portal-gun` will not work. I've searched poetry issues and it may be because of PEP 610? (I'm not sure).

Can anyone help?

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :clap: 

@louwers, as @tom-on-the-internet  says, in your original script you didn't have a Typer app. You were using the plain function `main` as a script.

You should create a Typer app (instead of using `typer.run()`) and then put that app object in your Poetry script. Check the docs guiding you through that process here: https://typer.tiangolo.com/tutorial/package/
