### ISSUE TITLE
[QUESTION] Unable to autocomplete commands

### ISSUE THREAD

**Issue by Kludex** [tiangolo/typer#161]
### First check

* [X] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the Typer documentation, with the integrated search.
* [X] I already searched in Google "How to X in Typer" and didn't find any information.
* [X] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I have an autocomplete for commands?

### Example

I have this simple app:

```python
from typer import Typer

app = Typer()

@app.command(help="Check the code style.")
def lint(folders: List[str]):
    Linter.run(folders)


@app.command(help="Format according to the code style.")
def format(folders: List[str]):
    Formatter.run(folders)
```
Also I have an entry point in the `setup.py`:
```python
    entry_points={"console_scripts": ["my_app=my_app.main:app"]}
```

But I'm unable to have autocompletion when I have something like this:
```bash
my_app li<tab here should add `nt`>
```

**Comment by jaywonchung** [comment]
Looks like you need this page.
https://typer.tiangolo.com/tutorial/options/autocompletion/

**Comment by Kludex** [comment]
I don't see how it is related... The problem is not the "option"

**Comment by jaywonchung** [comment]
Oh, sorry. Sleepy in the morning. In my case, adding the command name in the decorator gave me command completions.

```python
@app.command("lint")
def lint(...)
    pass
```

Hope it works for you.

**Comment by Kludex** [comment]
Not working yet :worried:

**Comment by tiangolo** [comment]
For autocompletion to work you have to install it, with:

```console
$ my_app --install-completion
```

Then you have to restart the terminal.

Check more about it here: https://typer.tiangolo.com/tutorial/package/#test-your-wheel-package

Also, it works for Zsh, Bash, Fish, and PowerShell. It won't work on `cmd.exe` in Windows, there's no way to support completion in it, that's why they deprecated it in favor of PowerShell.

---

Now, there's the additional package `typer-cli` (apart from `typer`). It creates a command `typer` that you can use with python scripts that use Typer, to run them, without having to install them as an app (very much similar to running with `python` directly).

But if you install completion for Typer-CLI, then when you use it to run your own scripts, e.g.:

```console
$ typer run my_app.py
```

...it will have completion for those scripts, magically.

**Comment by Kludex** [comment]
I'm **almost** sure it didn't work with the `--install-completion` and I just forgot to mention. But I'll check later. For now, I'm closing the issue, and once I have time I'll confirm.

**Comment by tiangolo** [comment]
Thanks! :rocket: :coffee:
