### ISSUE TITLE
[FEATURE] Register entry_points for improved usability

### ISSUE THREAD

**Issue by lsorber** [tiangolo/typer#191]
### Is your feature request related to a problem

No.

#### Context

[Invoke](https://github.com/pyinvoke/) allows you to create a module/package called `tasks`, after which you can run `invoke {command}` to run commands from that module/package. This is very useful to create common tasks you might want to run on your repository such as `invoke lint` or `invoke test`, and which can be reused in CI/CD.

The equivalent in Typer would be to call `python -m tasks {command}`, which doesn't provide the same level of convenience and is also harder for newcomers to remember.

#### Suggestion

Register [`entry_points` in `setup.py`](https://github.com/pyinvoke/invoke/blob/master/setup.py#L42) to enable an easy CLI interface such as
```
typer {module} {command}
```
so that you could run `typer tasks lint`. Taking it one step further you could make `tasks` the default module as Invoke does so that it shortens to `typer lint`.

### Describe alternatives you've considered

- Alternative package: [Invoke](https://github.com/pyinvoke/), which is great but unfortunately [does not support type annotations](https://github.com/pyinvoke/invoke/issues/357).
- Alternative workaround: use `python -m tasks {command}`.

**Comment by alextremblay** [comment]
it sounds like what you want is the [typer-cli](https://typer.tiangolo.com/typer-cli/)

does pretty much exactly what you want. if you have a python modules called tasks.py in your project's root, and have typer-cli installed, you can do `typer tasks.py {command}` to run a typer command defined in that tasks file

**Comment by lsorber** [comment]
> it sounds like what you want is the [typer-cli](https://typer.tiangolo.com/typer-cli/)
> 
> does pretty much exactly what you want. if you have a python modules called tasks.py in your project's root, and have typer-cli installed, you can do `typer tasks.py {command}` to run a typer command defined in that tasks file

That does come close indeed, but I'd like to see two changes to Typer CLI to improve the experience even more:

1. Next to the module-based command `typer tasks.py ...`, add a package-based command `typer tasks ...` (where `tasks` is a Python package).
2. Cosmetic detail: remove the `run` command from Typer CLI to reduce verbosity. E.g. `typer tasks lint` is easier than `typer tasks run lint`.

**Comment by zdog234** [comment]
Hmm I really like this idea (I've also been disappointed with pyinvoke). However, I think the only typer-specific part of this would be completions.

Someone's already got the name [`tasks`](https://pypi.org/project/tasks/) on pypi, otherwise I feel like `tasks` could be a good entrypoint for this -- it could also have the benefit of being CLI framework-agnostic.

One concern I have with allowing `typer tasks.py ...`, `typer tasks ...`, and `typer ...` is that it might be impossible to disambiguate `tasks` being a command name vs package name

**Comment by zdog234** [comment]
I can imagine having the options:

```bash
typer tasks.py ...
typer tasks ...
typer -- ...
```

or just

```bash
typer ...
```

**Comment by tiangolo** [comment]
Thanks for the discussion everyone!

Yep, indeed Typer-CLI would probably be the tool to do it.

Having support for a specific predefined `tasks` subcommand in Typer-CLI would be kind of a magic constant, it probably wouldn't add much when typing `tasks.py` is just 3 more characters, and as that's a file, tab completion could do it. And I would think it would be more intuitive, as it's quite explicit about what it's doing, it doesn't depend on a convention of a named file.

About having to add `run`, yep, it's not as convenient as just typing the thing directly, but it's necessary to be able to separate the path from the autogenerated sub-command that has all the automatic completion.

Also because there's another command to generate help docs for the script/program.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
