### ISSUE TITLE
[BUG] AttributeError: partially initialized module 'typer' has no attribute 'Typer' 

### ISSUE THREAD

**Issue by v3111707** [tiangolo/typer#207]
### Describe the bug

I am trying to run the code from example

### To Reproduce

* Create a file `typer.py` with:

```Python
import typer

app = typer.Typer()

@app.command()
def hello(name: str):
    typer.echo(f"Hello {name}")

if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python3 typer.py World
```

* It outputs:

```
Traceback (most recent call last):
  File "/Users/sergey/PycharmProjects/first_api/typer.py", line 1, in <module>
    import typer
  File "/Users/sergey/PycharmProjects/first_api/typer.py", line 3, in <module>
    app = typer.Typer()
AttributeError: partially initialized module 'typer' has no attribute 'Typer' (most likely due to a circular import)

```

* But I expected it to output:

```
Hello World
```

### Environment

* OS: macOS
* Typer Version: 0.3.2
* Python   3.9.0

**Comment by malthunayan** [comment]
@v3111707 you named your module as `typer.py` and python is trying to import the same file that contains your code. Each time it attempts to read the file `typer.py` (which, again, the import is actually trying to access), it will repeatedly try to import the file because it keeps reading the import line each time it tries to import it. Hence, the reason why you are seeing a `circular` import. To fix this, you can rename your module from `typer.py` to something like `foo.py`, `main.py`, ...

**Comment by daddycocoaman** [comment]
What @malthunayan said.

Circular imports is one of those Python things that's easy to mess up. I can't count the number of times I've accidentally named a file `logging.py` or something I shouldn't have.

**Comment by v3111707** [comment]
Thank you. I forgot about this peculiarity of import in python.

**Comment by tiangolo** [comment]
Thanks for the help here @malthunayan ! :clap: :bow: 

Thanks for reporting back and closing the issue @v3111707  :+1:
