### ISSUE TITLE
[QUESTION] Setting environement variable/starting new shell sesion/ some other workaround?

### ISSUE THREAD

**Issue by gardnerdev** [tiangolo/typer#235]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

How can I set environment variable within typer? 

Is it possible to do for example `export AWS_PROFILE=ROLE_A`  and use it in terminal?

**Comment by tiangolo** [comment]
Sorry, please follow the issue template and provide more information including a simple, self-contained code example of what you are doing and what you are trying to do. Otherwise, it's difficult to understand your use case and intentions.

If you still have problems please create a new issue and follow the template step by step.

Given that, I'm gonna close this one. ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
