### ISSUE TITLE
[QUESTION] How to store the authentication token in the application directory and use as dependency?

### ISSUE THREAD

**Issue by scuervo91** [tiangolo/typer#247]
### Description

How to store the authentication token in the application directory and use as dependency?.

I'd like to make a CLI app to be able to login with an oauth2. I'd like to know what is the procedure to store the token and use it as a 'dependency injection' like in FastAPI. 

In a [Question](https://github.com/tiangolo/typer/issues/160#issuecomment-751390380) the author says it is possible however i've not found any example. 

thanks

**Comment by edthamm** [comment]
Hi @scuervo91!

What you are asking about is not a typer specific question in my opinion.
If I understand your question correctly, you are asking:

How do I persist (long term) credentials so that I can use them across different invocations of my CLI application?

If this understanding is correct, and please correct me if it is not, my further questions are as follows.

- Get an understanding of what you are actually trying to do?
This sounds vague because I do not have a lot to go on. Are you looking to provide a CLI that works on multiple operating systems? Does your 'session' expire at regular intervals or are you trying to leave 'forever' credentials somewhere on disc?
- Think through the security implications of what you are about to do.
That is going to be very dependent on what you are doing. Credentials valid for 24h in a non-sensitive context, probably no worries. Credentials valid for ever and give access to healthcare data, probably more thought required. Not saying you should not do that thing just saying think about what exactly you are doing.

If I make the following assumptions:
- Linux only
- Relatively short lived tokens
- Relatively non-sensitive environment

1. On application start check if a config directory exists in the users home (e.g. /home/username/.yourapp). If not create it.
2. Check if the user is authenticate by looking for a valid token in a file in that directory. If not authenticate the user and store the token there.
3. Build a class that encapsulates the API you are trying to work with that handles.

All of this is not typer specific. From my experience with typer up to today I would not see how such things would be handled differently here than in any other cli framework.

The way I read the creators answer is basically also stating that you need to manage state and 'sessions' with backends by yourself.

Hope that helps somewhat.
Best.

**Comment by daddycocoaman** [comment]
Where security might be a concern (as it should be for tokens), you could try implementing the `keyring` package but you'll have to ensure that your app works across the different keyrings (Windows, Linux, Mac).

**Comment by tiangolo** [comment]
Thanks for the help here @edthamm and @daddycocoaman ! 👏  🙇 

If that solves the original problem, then you can close this issue @scuervo91  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
