### ISSUE TITLE
Is there a way to easily print all the arguments Typer has received.

### ISSUE THREAD

**Issue by joaqo** [tiangolo/typer#250]
Hi, first of all thank you for the absolutely great repo!

I am writing a machine learning training script, and it is very useful for this to be able to log the arguments each job got when it was ran, for reproducibility reasons. Before `typer` I used to use `argparse` and was able to do this just by doing:

```python
args = parser.parse_args()
print(args)
```

Is there a way to do this with typer? I tried using context as described in the doc and then just doing `print(ctx.args)` but it doesn't work, it seems to only store `the leftover arguments` whatever that means.

Thanks!

**Comment by captainCapitalism** [comment]
Hey, have you tried to use inbuild `locals` function?

Given some cli `cli.py`
```python
import typer
some_guy = "mike"

app = typer.Typer()


@app.command()
def my(a,b,c,d,e,f):
    print(locals())

if __name__ == "__main__":
    app()
   ```

run

```Console
python -m cli 1, 2, 3, 4, 5, 6
```
or
```Console
python -m t 1 2 3 4 5 6
```

**Comment by tiangolo** [comment]
Thanks for the help here @sathoune ! 👏  🙇 

@joaqo would that work for you?

Otherwise, you can access the parameters from the function and print them, does that work?

And otherwise, please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) that I can copy-paste to replicate it.

If that solves the original problem, then you can close this issue ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
