### ISSUE TITLE
Is there a way to run the command line argument parsing before my app's imports run?

### ISSUE THREAD

**Issue by joaqo** [tiangolo/typer#258]
Hi, first of all let me say that I absolutely love Typer.

Now, I am using Typer in the typical way:

```python
import typer
import torch

def main(some_number: int):
    print(some_number)

if __name__ == "__main__":
    typer.run(main)
```

This is really nice syntax wise, but it forces me to run all my imports before the user gets any feedback on the command they typed. In my current app my imports take about a second, and it sometimes happens that users type in a long running command, press enter, immediately leave, and don't see that they actually got an error on their command, as they left before the 1 second import time elapsed. It can result in a lot of execution time lost.

Is there a nice not too hacky way to avoid this?

**Comment by captainCapitalism** [comment]
Have you considered using imports inside the functions?
Given `slow_import.py`
```python
import time
print("waiting")
time.sleep(2)


def print_number(n):
    print("number: ", n)
```

and `main.py`
```python
import typer

app = typer.Typer()

def do_the_math(some_number):
    import slow_import

    slow_import.print_number(some_number)


@app.command()
def main(some_number: int):
    print("Started function")
    do_the_math(some_number)
    do_the_math(some_number)


if __name__ == "__main__":
    app()
```

Execution will validate arguments before the import.

I did not have such an issue myself but look into async imports - [stack-overflow](
https://stackoverflow.com/questions/50026485/asynchronous-import-in-python
)
Given the same `slow_module.py` and now different `main.py`
```python
import typer

import threading
import importlib

app = typer.Typer()


def begin_load_slow_module():
    global slow_module_thread
    slow_module_thread = threading.Thread(target=load_slow_module_thread)
    slow_module_thread.start()


def load_slow_module_thread():
    global slow_import
    print("start importing")
    slow_import = importlib.import_module('slow_import')
    print("done importing")


def wait_slow_import():
    print('wait')
    slow_module_thread.join()
    print('done')

def do_the_loading():
    begin_load_slow_module()
    wait_slow_import()


def do_the_math(some_number):
    slow_import.print_number(some_number)



@app.command()
def main(some_number: int):
    do_the_loading()
    print("Started function")
    do_the_math(some_number)
    do_the_math(some_number)


if __name__ == "__main__":
    app()
```

In the end it does the same thing, but you are using all the benefits of autocompletion in your IDE and seems to me much more hacky than above.

I am not aware of any argument validators that run before the Typer execution. You could probably create some validator that runs before Typer by accessing function definition  but I think this is out of the scope of your needs. 
Given `more_complex_app.py`
```
import typer


def annoying_multi_argument_function(
    number: int,
    other_number: int = typer.Argument(..., min=15),
    string: str = typer.Option(...,)
):
    print(number)
    print(other_number)
    print(string)
```
and `validator.py`
```
from more_complex_app import annoying_multi_argument_function

print(annoying_multi_argument_function.__annotations__)
print(annoying_multi_argument_function.__defaults__)
print(annoying_multi_argument_function.__defaults__[0].min)
print(annoying_multi_argument_function.__defaults__[1].default)

```
In addition you cannot execute it like that in runtime because of the same import issue that you encounter, so there would be need for some prepared metadata of these functions.

**Comment by joaqo** [comment]
Hi thanks a lot for the help. These methods can work but they kinda require me to restructure large parts of my code base. For example I use an enum in my codebase, which I also use in Typer for an argument type. Therefore I have to import this enum before I define my typer commands, but importing this enum imports my whole codebase, which makes typer slow to start. I could place the definition for this enum in a separate file that doesn't import the rest of my code base to avoid this, but as I said, I'd be stepping foot on a slippery slope of restructuring my core codebase in non obvious ways just to make Typer run fast.

I think I'm gonna skip this for now. Thanks @captainCapitalism

@tiangolo I am absolutely in love with this library, but if you manage to find a way to chose when typer runs, which the more I think about the harder it looks to implement on your side, it'd become my 100% go to cli library.

Cheers!

**Comment by tiangolo** [comment]
Thanks for the help here @sathoune ! 👏  🙇 

And indeed, if importing your modules is slow, doing the imports inside of the functions would be the way to go.

I'm glad you're liking Typer @joaqo! :rocket: 

If you need an enum from a module that is slow to load, you can move that enum to somewhere else that doesn't import your slow modules.

Also, if your modules are slow to load, there's a high chance you doing something wrong, with heavy side effects as part of the module definition, e.g. loading a machine learning model in a global variable. In that case, you could refactor that to instead of doing that heavy stuff (e.g. loading an ML model at the top level of a module) doing that heavy work inside of a function. And you could decorate the function with an `lru_cache` to make sure the heavy code is executed only the first time, but afterwards it only returns the same object that it had created.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
