### ISSUE TITLE
[FEATURE] Please enable github discussions

### ISSUE THREAD

**Issue by ssbarnea** [tiangolo/typer#265]
### Is your feature request related to a problem

Using the issue tracking for support is less than ideal and scales really badly once a projects gets more attention. 

Another problem with that is that due to its nature, old questions are easily to miss as being closed tickets and search tools do not count them based on popularity.

### The solution you would like

Just go to "Settings" tab and enable discussions. Optionally you can update the https://github.com/tiangolo/typer/tree/master/.github/ISSUE_TEMPLATE and update the question template to recommend opening a discussion. Example https://github.com/ansible-community/ansible-lint/blob/master/.github/ISSUE_TEMPLATE/config.yml#L7-L9

### Describe alternatives you've considered

N/A

**Comment by tiangolo** [comment]
Thanks, but it's intentional, discussions don't allow creating a template, and when people come to ask questions there's a lot of back and forth just trying to understand the original intention, question, and problem. But if they follow the template properly, that guides people to provide all the information necessary.

Once they add support for templates in discussions I'll move questions in my repos to them. https://github.com/community/community/discussions/2838

But before that, it's just a lot of extra effort from me or anyone that comes to help just to try to understand what was the question, even before trying to answer it.

For example, I enabled discussions in FastAPI, and it's never as good as questions in issues for that same problem, it's normally difficult to help people there.

So, for now, I'll pass on this request, but thanks for the interest! ☕
