### ISSUE TITLE
Auto-document command with docstrings

### ISSUE THREAD

**Issue by ines** [tiangolo/typer#3]
### Describe the bug

It seems like docstrings are currently not used to auto-document the commands when typing `--help`. Or maybe there's a setting that I'm missing?

### To Reproduce

* Create a file `main.py` with:

```Python
import typer

app = typer.Typer()


@app.command()
def hello(name: str):
    """This is a docstring."""
    typer.echo(f"Hello {name}")


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py --help
```

* It outputs:

```
Usage: main.py [OPTIONS] NAME

Options:
  --help  Show this message and exit.
```

* But I expected it to output:

```diff
Usage: main.py [OPTIONS] NAME

+  This is a docstring.

Options:
  --help  Show this message and exit.
```

### Expected behavior

The equivalent in `click` and `plac` would use `"This is a docstring"` to describe the command when you run it with `--help`.

### Environment

* OS: macOs
* Typer Version: 0.0.4
* Python version: 3.6.0

**Comment by tiangolo** [comment]
Thanks for the well-written report! I didn't know you could use `diff` for fenced code. :memo: 

It should be fixed in version 0.0.5 (just released).

It's now documented too: https://typer.tiangolo.com/tutorial/first-steps/#document-your-cli-app

And that same example is used to test the functionality.
