### ISSUE TITLE
[BUG] typer 0.3.2 has requirement click<7.2.0,>=7.1.1, but you have click 8.0.1

### ISSUE THREAD

**Issue by mborsetti** [tiangolo/typer#313]
Please support current package releases and/or remove overly restrictive requirements!

**Comment by musicinmybrain** [comment]
A nontrivial patch is required (https://github.com/tiangolo/typer/issues/280) since this library depends heavily on click 7.x internals.

The project is maintained solely by @tiangolo.

- Via Twitter, they have expressed an intent to spend more time on Typer and FastAPI
- They have been active recently in https://github.com/tiangolo/fastapi/
- They made a new release of https://github.com/tiangolo/typer-cli/ last month (but without addressing the click 8.x issue)
- As far as I know, they have not responded to issues or PRs here in many, many months (https://github.com/tiangolo/typer/issues/300)

It’s not clear if this project will be maintained in a sustainable way in the future or not.

**Comment by honnibal** [comment]
@tiangolo If the patch is non-trivial, I suggest vendoring click v7 within typer for now? This way a quick fix can be released that relieves the dependency hell, because typer can drop the external click v7 dependency.

**Comment by tiangolo** [comment]
Thanks for the discussion and interest here everyone! :cake: 

I just released Typer `0.4.0`, which is compatible with **both** Click 7 and Click 8. :tada:
