### ISSUE TITLE
[FEATURE] keyword args instead of only positional args

### ISSUE THREAD

**Issue by fschlz** [tiangolo/typer#314]
I would like to be able to pass arguments like this:

``python main.py hello --name James``

instead of

``python main.py hello James``

As it is there is no semantic separation between a command and its arguments.

**Comment by captainCapitalism** [comment]
Arguments are by default required, and Options are optional. To change this you can pass `typer.Argument("Something")` and `typer.Option(...)` as default values. https://typer.tiangolo.com/tutorial/commands/options/

```python
import typer

app = typer.Typer()


@app.command()
def main(surname: str = typer.Argument("Surname"), name: str = typer.Option(...)):
    typer.echo(f'{name} {surname}')


if __name__ == "__main__":
    app()
```

**Comment by fschlz** [comment]
> Arguments are by default required, and Options are optional. To change this you can pass `typer.Argument("Something")` and `typer.Option(...)` as default values. https://typer.tiangolo.com/tutorial/commands/options/
> 
> ```python
> import typer
> 
> app = typer.Typer()
> 
> 
> @app.command()
> def main(surname: str = typer.Argument("Surname"), name: str = typer.Option(...)):
>     typer.echo(f'{name} {surname}')
> 
> 
> if __name__ == "__main__":
>     app()
> ```

Not what I asked. It's not about passing optional Args or not.
I think it would be better if we could pass arguments to the script according to their names in Python, i.e. `--name James`, instead we have to pass them based on position which I think is less safe and also less visually obvious.

**Comment by LandingEllipse** [comment]
@fschlz I believe captainCapitalism addressed exactly what you asked. The animated usage example [shown here](https://typer.tiangolo.com/typer-cli/#run-with-python) does literally what you appear to be after, using `typer.Option()`. 

Named arguments / options are the bread and butter of utilities like Typer, so your claim that it is not an existing feature suggests to me that you either have not put much effort into reading the documentation, or that we are dealing with a language barrier / articulation issue. If it's the latter, please elaborate on exactly what you are looking to achieve, and why `typer.Option()` is not sufficient.

**Comment by fschlz** [comment]
> @fschlz I believe captainCapitalism addressed exactly what you asked. The animated usage example [shown here](https://typer.tiangolo.com/typer-cli/#run-with-python) does literally what you appear to be after, using `typer.Option()`.
> 
> Named arguments / options are the bread and butter of utilities like Typer, so your claim that it is not an existing feature suggests to me that you either have not put much effort into reading the documentation, or that we are dealing with a language barrier / articulation issue. If it's the latter, please elaborate on exactly what you are looking to achieve, and why `typer.Option()` is not sufficient.

I see that `typer.Option()` does that. It just threw me off that I didn't have to pass each argument in the same way with the `--` before it, optional or not. I realize I can force that.

I'm closing this. Thx guys

**Comment by caph1993** [comment]
I think that this issue isn't resolved, because the desired feature is to make it possible to pass a required argument either by position or by name.

```py
import typer
app = typer.Typer()

@app.command()
def hello(name: str):
    print(f"Hello {name}")

if __name__ == "__main__":
    app()
```

In Python we can call `hello("Carlos")` or `hello(name="Carlos")`, and both will produce the same result.

In typer, however, we have the following behavior
- if the signature is `def hello(name: str):`, we can call `hello Carlos` but we can't call `hello --name Carlos`. 
- if the signature is `def hello(name: str="Alan"):`, we can call `hello` and `hello --name Carlos` but we can't call `hello Carlos`.

It would more natural (or more Pythonic at least) if typer followed Python's argument parsing:
- for `def hello(name: str):`, allow `hello Carlos` and `hello --name Carlos`, but not `hello`. 
- for `def hello(name: str="Alan"):`, allow `hello`, `hello --name Carlos` and `hello Carlos`. 
- for `def hello(*, name: str="Alan"):`, allow `hello`, `hello --name Carlos` but not `hello Carlos`.

**Comment by warvariuc** [comment]
Not being able to pass arguments with names doesn't feel pythonic. 

```
>>> def func(a):
...     print(a)
...
>>> func(1)
1
>>> func(a=1)
1
>>>
```

Being able to use names helps when there are lots of positional arguments and it's difficult to understand which is which.
