### ISSUE TITLE
[QUESTION] Where can mypy find library stubs for typer?

### ISSUE THREAD

**Issue by OdinTech3** [tiangolo/typer#99]
### First check

* [x ] I used the GitHub search to find a similar issue and didn't find it.
* [x ] I searched the Typer documentation, with the integrated search.
* [ x] I already searched in Google "How to X in Typer" and didn't find any information.
* [ x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

Where can mypy find library stubs for typer? Currently when I run mypy in my projects root directory I get the error `Cannot find implementation or library stub for module named 'typer'`

**Comment by bruceadams** [comment]
I do not see this problem. (I see a _different_ problem, but never mind that right now).

I what you ask for here is addressed by issue #53 which was fixed by pull request #58. Can you try picking up a newer release of `typer` (I have `0.2.1`)? (Or maybe a newer `mypy`, I have `0.770`?)

**Comment by OdinTech3** [comment]
Okay I will update my version and check things out

**Comment by tiangolo** [comment]
Thanks for the help here @bruceadams ! :clap: :bow: 

Thanks for reporting back and closing the issue @OdinTech3  :+1:

**Comment by Jarmos-san** [comment]
Stumbled across this when searching for a solution on Google & figured what went wrong on my end. So, here's what I found was wrong & hope it helps someone in the near future.

I use Neovim & a couple of plugins (more specifically [`null-ls`](https://github.com/jose-elias-alvarez/null-ls.nvim) is the culprit here). You need to configure it to use the `mypy` executable located under the `.venv/bin` directory.

So, here's how I fixed it on my end:

```lua
-- In your init.lua, modify &  add these code snippet
local packer = require("packer")

packer.startup({
  function(use)
    use({
      "jose-elias-alvarez/null-ls.nvim",
      config = function()
        require("null-ls").setup({
          sources = {
            require("null-ls").builtins.diagnostics.mypy.with({
              prefer_local = ".venv/bin"
            })
          }
        })
      end,
      requires = { "nvim-lua/plenary.nvim" }
    })
  end
})
```
